// Generated by gencpp from file web_robo/ListDirectory.msg
// DO NOT EDIT!


#ifndef WEB_ROBO_MESSAGE_LISTDIRECTORY_H
#define WEB_ROBO_MESSAGE_LISTDIRECTORY_H

#include <ros/service_traits.h>


#include <web_robo/ListDirectoryRequest.h>
#include <web_robo/ListDirectoryResponse.h>


namespace web_robo
{

struct ListDirectory
{

typedef ListDirectoryRequest Request;
typedef ListDirectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListDirectory
} // namespace web_robo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::web_robo::ListDirectory > {
  static const char* value()
  {
    return "a8e8a0ad7d18ff7b91f5d9d166c371c1";
  }

  static const char* value(const ::web_robo::ListDirectory&) { return value(); }
};

template<>
struct DataType< ::web_robo::ListDirectory > {
  static const char* value()
  {
    return "web_robo/ListDirectory";
  }

  static const char* value(const ::web_robo::ListDirectory&) { return value(); }
};


// service_traits::MD5Sum< ::web_robo::ListDirectoryRequest> should match 
// service_traits::MD5Sum< ::web_robo::ListDirectory > 
template<>
struct MD5Sum< ::web_robo::ListDirectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::web_robo::ListDirectory >::value();
  }
  static const char* value(const ::web_robo::ListDirectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::web_robo::ListDirectoryRequest> should match 
// service_traits::DataType< ::web_robo::ListDirectory > 
template<>
struct DataType< ::web_robo::ListDirectoryRequest>
{
  static const char* value()
  {
    return DataType< ::web_robo::ListDirectory >::value();
  }
  static const char* value(const ::web_robo::ListDirectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::web_robo::ListDirectoryResponse> should match 
// service_traits::MD5Sum< ::web_robo::ListDirectory > 
template<>
struct MD5Sum< ::web_robo::ListDirectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::web_robo::ListDirectory >::value();
  }
  static const char* value(const ::web_robo::ListDirectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::web_robo::ListDirectoryResponse> should match 
// service_traits::DataType< ::web_robo::ListDirectory > 
template<>
struct DataType< ::web_robo::ListDirectoryResponse>
{
  static const char* value()
  {
    return DataType< ::web_robo::ListDirectory >::value();
  }
  static const char* value(const ::web_robo::ListDirectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEB_ROBO_MESSAGE_LISTDIRECTORY_H
