// Generated by gencpp from file web_robo/ListDirectoryResponse.msg
// DO NOT EDIT!


#ifndef WEB_ROBO_MESSAGE_LISTDIRECTORYRESPONSE_H
#define WEB_ROBO_MESSAGE_LISTDIRECTORYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace web_robo
{
template <class ContainerAllocator>
struct ListDirectoryResponse_
{
  typedef ListDirectoryResponse_<ContainerAllocator> Type;

  ListDirectoryResponse_()
    : list_of_files()  {
    }
  ListDirectoryResponse_(const ContainerAllocator& _alloc)
    : list_of_files(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _list_of_files_type;
  _list_of_files_type list_of_files;





  typedef boost::shared_ptr< ::web_robo::ListDirectoryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::web_robo::ListDirectoryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ListDirectoryResponse_

typedef ::web_robo::ListDirectoryResponse_<std::allocator<void> > ListDirectoryResponse;

typedef boost::shared_ptr< ::web_robo::ListDirectoryResponse > ListDirectoryResponsePtr;
typedef boost::shared_ptr< ::web_robo::ListDirectoryResponse const> ListDirectoryResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::web_robo::ListDirectoryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::web_robo::ListDirectoryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace web_robo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::web_robo::ListDirectoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::web_robo::ListDirectoryResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::web_robo::ListDirectoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::web_robo::ListDirectoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::web_robo::ListDirectoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::web_robo::ListDirectoryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::web_robo::ListDirectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92bb8071707468b8581f4ae630cd3d5d";
  }

  static const char* value(const ::web_robo::ListDirectoryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92bb8071707468b8ULL;
  static const uint64_t static_value2 = 0x581f4ae630cd3d5dULL;
};

template<class ContainerAllocator>
struct DataType< ::web_robo::ListDirectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "web_robo/ListDirectoryResponse";
  }

  static const char* value(const ::web_robo::ListDirectoryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::web_robo::ListDirectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] list_of_files\n\
\n\
";
  }

  static const char* value(const ::web_robo::ListDirectoryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::web_robo::ListDirectoryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.list_of_files);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ListDirectoryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::web_robo::ListDirectoryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::web_robo::ListDirectoryResponse_<ContainerAllocator>& v)
  {
    s << indent << "list_of_files[]" << std::endl;
    for (size_t i = 0; i < v.list_of_files.size(); ++i)
    {
      s << indent << "  list_of_files[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.list_of_files[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEB_ROBO_MESSAGE_LISTDIRECTORYRESPONSE_H
