// Generated by gencpp from file web_robo/ListHome.msg
// DO NOT EDIT!


#ifndef WEB_ROBO_MESSAGE_LISTHOME_H
#define WEB_ROBO_MESSAGE_LISTHOME_H

#include <ros/service_traits.h>


#include <web_robo/ListHomeRequest.h>
#include <web_robo/ListHomeResponse.h>


namespace web_robo
{

struct ListHome
{

typedef ListHomeRequest Request;
typedef ListHomeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListHome
} // namespace web_robo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::web_robo::ListHome > {
  static const char* value()
  {
    return "264ac43195b2a02803670c84d5678c9a";
  }

  static const char* value(const ::web_robo::ListHome&) { return value(); }
};

template<>
struct DataType< ::web_robo::ListHome > {
  static const char* value()
  {
    return "web_robo/ListHome";
  }

  static const char* value(const ::web_robo::ListHome&) { return value(); }
};


// service_traits::MD5Sum< ::web_robo::ListHomeRequest> should match 
// service_traits::MD5Sum< ::web_robo::ListHome > 
template<>
struct MD5Sum< ::web_robo::ListHomeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::web_robo::ListHome >::value();
  }
  static const char* value(const ::web_robo::ListHomeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::web_robo::ListHomeRequest> should match 
// service_traits::DataType< ::web_robo::ListHome > 
template<>
struct DataType< ::web_robo::ListHomeRequest>
{
  static const char* value()
  {
    return DataType< ::web_robo::ListHome >::value();
  }
  static const char* value(const ::web_robo::ListHomeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::web_robo::ListHomeResponse> should match 
// service_traits::MD5Sum< ::web_robo::ListHome > 
template<>
struct MD5Sum< ::web_robo::ListHomeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::web_robo::ListHome >::value();
  }
  static const char* value(const ::web_robo::ListHomeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::web_robo::ListHomeResponse> should match 
// service_traits::DataType< ::web_robo::ListHome > 
template<>
struct DataType< ::web_robo::ListHomeResponse>
{
  static const char* value()
  {
    return DataType< ::web_robo::ListHome >::value();
  }
  static const char* value(const ::web_robo::ListHomeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEB_ROBO_MESSAGE_LISTHOME_H
