// Generated by gencpp from file web_robo/WebCommandResponse.msg
// DO NOT EDIT!


#ifndef WEB_ROBO_MESSAGE_WEBCOMMANDRESPONSE_H
#define WEB_ROBO_MESSAGE_WEBCOMMANDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace web_robo
{
template <class ContainerAllocator>
struct WebCommandResponse_
{
  typedef WebCommandResponse_<ContainerAllocator> Type;

  WebCommandResponse_()
    : received_status(false)  {
    }
  WebCommandResponse_(const ContainerAllocator& _alloc)
    : received_status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _received_status_type;
  _received_status_type received_status;





  typedef boost::shared_ptr< ::web_robo::WebCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::web_robo::WebCommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WebCommandResponse_

typedef ::web_robo::WebCommandResponse_<std::allocator<void> > WebCommandResponse;

typedef boost::shared_ptr< ::web_robo::WebCommandResponse > WebCommandResponsePtr;
typedef boost::shared_ptr< ::web_robo::WebCommandResponse const> WebCommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::web_robo::WebCommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::web_robo::WebCommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace web_robo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::web_robo::WebCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::web_robo::WebCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::web_robo::WebCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::web_robo::WebCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::web_robo::WebCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::web_robo::WebCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::web_robo::WebCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fadcd216e085028f01e227602e8be59b";
  }

  static const char* value(const ::web_robo::WebCommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfadcd216e085028fULL;
  static const uint64_t static_value2 = 0x01e227602e8be59bULL;
};

template<class ContainerAllocator>
struct DataType< ::web_robo::WebCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "web_robo/WebCommandResponse";
  }

  static const char* value(const ::web_robo::WebCommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::web_robo::WebCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool received_status\n\
\n\
";
  }

  static const char* value(const ::web_robo::WebCommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::web_robo::WebCommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.received_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WebCommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::web_robo::WebCommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::web_robo::WebCommandResponse_<ContainerAllocator>& v)
  {
    s << indent << "received_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.received_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEB_ROBO_MESSAGE_WEBCOMMANDRESPONSE_H
