// Generated by gencpp from file web_robo/WebCommand.msg
// DO NOT EDIT!


#ifndef WEB_ROBO_MESSAGE_WEBCOMMAND_H
#define WEB_ROBO_MESSAGE_WEBCOMMAND_H

#include <ros/service_traits.h>


#include <web_robo/WebCommandRequest.h>
#include <web_robo/WebCommandResponse.h>


namespace web_robo
{

struct WebCommand
{

typedef WebCommandRequest Request;
typedef WebCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WebCommand
} // namespace web_robo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::web_robo::WebCommand > {
  static const char* value()
  {
    return "44d2b40d74222232b1f3ee0bac50b6e7";
  }

  static const char* value(const ::web_robo::WebCommand&) { return value(); }
};

template<>
struct DataType< ::web_robo::WebCommand > {
  static const char* value()
  {
    return "web_robo/WebCommand";
  }

  static const char* value(const ::web_robo::WebCommand&) { return value(); }
};


// service_traits::MD5Sum< ::web_robo::WebCommandRequest> should match 
// service_traits::MD5Sum< ::web_robo::WebCommand > 
template<>
struct MD5Sum< ::web_robo::WebCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::web_robo::WebCommand >::value();
  }
  static const char* value(const ::web_robo::WebCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::web_robo::WebCommandRequest> should match 
// service_traits::DataType< ::web_robo::WebCommand > 
template<>
struct DataType< ::web_robo::WebCommandRequest>
{
  static const char* value()
  {
    return DataType< ::web_robo::WebCommand >::value();
  }
  static const char* value(const ::web_robo::WebCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::web_robo::WebCommandResponse> should match 
// service_traits::MD5Sum< ::web_robo::WebCommand > 
template<>
struct MD5Sum< ::web_robo::WebCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::web_robo::WebCommand >::value();
  }
  static const char* value(const ::web_robo::WebCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::web_robo::WebCommandResponse> should match 
// service_traits::DataType< ::web_robo::WebCommand > 
template<>
struct DataType< ::web_robo::WebCommandResponse>
{
  static const char* value()
  {
    return DataType< ::web_robo::WebCommand >::value();
  }
  static const char* value(const ::web_robo::WebCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEB_ROBO_MESSAGE_WEBCOMMAND_H
