// Generated by gencpp from file web_robo/WebFeedbackResponse.msg
// DO NOT EDIT!


#ifndef WEB_ROBO_MESSAGE_WEBFEEDBACKRESPONSE_H
#define WEB_ROBO_MESSAGE_WEBFEEDBACKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace web_robo
{
template <class ContainerAllocator>
struct WebFeedbackResponse_
{
  typedef WebFeedbackResponse_<ContainerAllocator> Type;

  WebFeedbackResponse_()
    : user_response(false)  {
    }
  WebFeedbackResponse_(const ContainerAllocator& _alloc)
    : user_response(false)  {
  (void)_alloc;
    }



   typedef uint8_t _user_response_type;
  _user_response_type user_response;





  typedef boost::shared_ptr< ::web_robo::WebFeedbackResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::web_robo::WebFeedbackResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WebFeedbackResponse_

typedef ::web_robo::WebFeedbackResponse_<std::allocator<void> > WebFeedbackResponse;

typedef boost::shared_ptr< ::web_robo::WebFeedbackResponse > WebFeedbackResponsePtr;
typedef boost::shared_ptr< ::web_robo::WebFeedbackResponse const> WebFeedbackResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::web_robo::WebFeedbackResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::web_robo::WebFeedbackResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace web_robo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::web_robo::WebFeedbackResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::web_robo::WebFeedbackResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::web_robo::WebFeedbackResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::web_robo::WebFeedbackResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::web_robo::WebFeedbackResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::web_robo::WebFeedbackResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::web_robo::WebFeedbackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d0bfd0e81623242bce54b48cf8a4541";
  }

  static const char* value(const ::web_robo::WebFeedbackResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d0bfd0e81623242ULL;
  static const uint64_t static_value2 = 0xbce54b48cf8a4541ULL;
};

template<class ContainerAllocator>
struct DataType< ::web_robo::WebFeedbackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "web_robo/WebFeedbackResponse";
  }

  static const char* value(const ::web_robo::WebFeedbackResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::web_robo::WebFeedbackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool user_response\n\
";
  }

  static const char* value(const ::web_robo::WebFeedbackResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::web_robo::WebFeedbackResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.user_response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WebFeedbackResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::web_robo::WebFeedbackResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::web_robo::WebFeedbackResponse_<ContainerAllocator>& v)
  {
    s << indent << "user_response: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.user_response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEB_ROBO_MESSAGE_WEBFEEDBACKRESPONSE_H
