// Generated by gencpp from file robot_base_servo/speed.msg
// DO NOT EDIT!


#ifndef ROBOT_BASE_SERVO_MESSAGE_SPEED_H
#define ROBOT_BASE_SERVO_MESSAGE_SPEED_H

#include <ros/service_traits.h>


#include <robot_base_servo/speedRequest.h>
#include <robot_base_servo/speedResponse.h>


namespace robot_base_servo
{

struct speed
{

typedef speedRequest Request;
typedef speedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct speed
} // namespace robot_base_servo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_base_servo::speed > {
  static const char* value()
  {
    return "f4e6290d51987b0b075a95509c473580";
  }

  static const char* value(const ::robot_base_servo::speed&) { return value(); }
};

template<>
struct DataType< ::robot_base_servo::speed > {
  static const char* value()
  {
    return "robot_base_servo/speed";
  }

  static const char* value(const ::robot_base_servo::speed&) { return value(); }
};


// service_traits::MD5Sum< ::robot_base_servo::speedRequest> should match 
// service_traits::MD5Sum< ::robot_base_servo::speed > 
template<>
struct MD5Sum< ::robot_base_servo::speedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_base_servo::speed >::value();
  }
  static const char* value(const ::robot_base_servo::speedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_base_servo::speedRequest> should match 
// service_traits::DataType< ::robot_base_servo::speed > 
template<>
struct DataType< ::robot_base_servo::speedRequest>
{
  static const char* value()
  {
    return DataType< ::robot_base_servo::speed >::value();
  }
  static const char* value(const ::robot_base_servo::speedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_base_servo::speedResponse> should match 
// service_traits::MD5Sum< ::robot_base_servo::speed > 
template<>
struct MD5Sum< ::robot_base_servo::speedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_base_servo::speed >::value();
  }
  static const char* value(const ::robot_base_servo::speedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_base_servo::speedResponse> should match 
// service_traits::DataType< ::robot_base_servo::speed > 
template<>
struct DataType< ::robot_base_servo::speedResponse>
{
  static const char* value()
  {
    return DataType< ::robot_base_servo::speed >::value();
  }
  static const char* value(const ::robot_base_servo::speedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_BASE_SERVO_MESSAGE_SPEED_H
