// Generated by gencpp from file robot_base_servo/voltage.msg
// DO NOT EDIT!


#ifndef ROBOT_BASE_SERVO_MESSAGE_VOLTAGE_H
#define ROBOT_BASE_SERVO_MESSAGE_VOLTAGE_H

#include <ros/service_traits.h>


#include <robot_base_servo/voltageRequest.h>
#include <robot_base_servo/voltageResponse.h>


namespace robot_base_servo
{

struct voltage
{

typedef voltageRequest Request;
typedef voltageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct voltage
} // namespace robot_base_servo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_base_servo::voltage > {
  static const char* value()
  {
    return "00886afbc7627a03f5753fba171f3ab9";
  }

  static const char* value(const ::robot_base_servo::voltage&) { return value(); }
};

template<>
struct DataType< ::robot_base_servo::voltage > {
  static const char* value()
  {
    return "robot_base_servo/voltage";
  }

  static const char* value(const ::robot_base_servo::voltage&) { return value(); }
};


// service_traits::MD5Sum< ::robot_base_servo::voltageRequest> should match 
// service_traits::MD5Sum< ::robot_base_servo::voltage > 
template<>
struct MD5Sum< ::robot_base_servo::voltageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_base_servo::voltage >::value();
  }
  static const char* value(const ::robot_base_servo::voltageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_base_servo::voltageRequest> should match 
// service_traits::DataType< ::robot_base_servo::voltage > 
template<>
struct DataType< ::robot_base_servo::voltageRequest>
{
  static const char* value()
  {
    return DataType< ::robot_base_servo::voltage >::value();
  }
  static const char* value(const ::robot_base_servo::voltageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_base_servo::voltageResponse> should match 
// service_traits::MD5Sum< ::robot_base_servo::voltage > 
template<>
struct MD5Sum< ::robot_base_servo::voltageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_base_servo::voltage >::value();
  }
  static const char* value(const ::robot_base_servo::voltageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_base_servo::voltageResponse> should match 
// service_traits::DataType< ::robot_base_servo::voltage > 
template<>
struct DataType< ::robot_base_servo::voltageResponse>
{
  static const char* value()
  {
    return DataType< ::robot_base_servo::voltage >::value();
  }
  static const char* value(const ::robot_base_servo::voltageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_BASE_SERVO_MESSAGE_VOLTAGE_H
