// Generated by gencpp from file robo_waiter/PauseResponse.msg
// DO NOT EDIT!


#ifndef ROBO_WAITER_MESSAGE_PAUSERESPONSE_H
#define ROBO_WAITER_MESSAGE_PAUSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robo_waiter
{
template <class ContainerAllocator>
struct PauseResponse_
{
  typedef PauseResponse_<ContainerAllocator> Type;

  PauseResponse_()
    : reply()  {
    }
  PauseResponse_(const ContainerAllocator& _alloc)
    : reply(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _reply_type;
  _reply_type reply;





  typedef boost::shared_ptr< ::robo_waiter::PauseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robo_waiter::PauseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PauseResponse_

typedef ::robo_waiter::PauseResponse_<std::allocator<void> > PauseResponse;

typedef boost::shared_ptr< ::robo_waiter::PauseResponse > PauseResponsePtr;
typedef boost::shared_ptr< ::robo_waiter::PauseResponse const> PauseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robo_waiter::PauseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robo_waiter::PauseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robo_waiter

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robo_waiter': ['/home/katomaran-ros/catkin_ws8/src/robo_waiter/msg', '/home/katomaran-ros/catkin_ws8/src/robo_waiter/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robo_waiter::PauseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robo_waiter::PauseResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robo_waiter::PauseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robo_waiter::PauseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robo_waiter::PauseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robo_waiter::PauseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robo_waiter::PauseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f5cc45a827e5f04b00100078ec13f4c";
  }

  static const char* value(const ::robo_waiter::PauseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f5cc45a827e5f04ULL;
  static const uint64_t static_value2 = 0xb00100078ec13f4cULL;
};

template<class ContainerAllocator>
struct DataType< ::robo_waiter::PauseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robo_waiter/PauseResponse";
  }

  static const char* value(const ::robo_waiter::PauseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robo_waiter::PauseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string reply\n\
\n\
";
  }

  static const char* value(const ::robo_waiter::PauseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robo_waiter::PauseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reply);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PauseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robo_waiter::PauseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robo_waiter::PauseResponse_<ContainerAllocator>& v)
  {
    s << indent << "reply: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.reply);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBO_WAITER_MESSAGE_PAUSERESPONSE_H
