// Generated by gencpp from file robo_waiter/Pause.msg
// DO NOT EDIT!


#ifndef ROBO_WAITER_MESSAGE_PAUSE_H
#define ROBO_WAITER_MESSAGE_PAUSE_H

#include <ros/service_traits.h>


#include <robo_waiter/PauseRequest.h>
#include <robo_waiter/PauseResponse.h>


namespace robo_waiter
{

struct Pause
{

typedef PauseRequest Request;
typedef PauseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Pause
} // namespace robo_waiter


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robo_waiter::Pause > {
  static const char* value()
  {
    return "3dfb9d0014ecbba1e3c8cb189553972f";
  }

  static const char* value(const ::robo_waiter::Pause&) { return value(); }
};

template<>
struct DataType< ::robo_waiter::Pause > {
  static const char* value()
  {
    return "robo_waiter/Pause";
  }

  static const char* value(const ::robo_waiter::Pause&) { return value(); }
};


// service_traits::MD5Sum< ::robo_waiter::PauseRequest> should match 
// service_traits::MD5Sum< ::robo_waiter::Pause > 
template<>
struct MD5Sum< ::robo_waiter::PauseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robo_waiter::Pause >::value();
  }
  static const char* value(const ::robo_waiter::PauseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robo_waiter::PauseRequest> should match 
// service_traits::DataType< ::robo_waiter::Pause > 
template<>
struct DataType< ::robo_waiter::PauseRequest>
{
  static const char* value()
  {
    return DataType< ::robo_waiter::Pause >::value();
  }
  static const char* value(const ::robo_waiter::PauseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robo_waiter::PauseResponse> should match 
// service_traits::MD5Sum< ::robo_waiter::Pause > 
template<>
struct MD5Sum< ::robo_waiter::PauseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robo_waiter::Pause >::value();
  }
  static const char* value(const ::robo_waiter::PauseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robo_waiter::PauseResponse> should match 
// service_traits::DataType< ::robo_waiter::Pause > 
template<>
struct DataType< ::robo_waiter::PauseResponse>
{
  static const char* value()
  {
    return DataType< ::robo_waiter::Pause >::value();
  }
  static const char* value(const ::robo_waiter::PauseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBO_WAITER_MESSAGE_PAUSE_H
