// Generated by gencpp from file robo_waiter/Table.msg
// DO NOT EDIT!


#ifndef ROBO_WAITER_MESSAGE_TABLE_H
#define ROBO_WAITER_MESSAGE_TABLE_H

#include <ros/service_traits.h>


#include <robo_waiter/TableRequest.h>
#include <robo_waiter/TableResponse.h>


namespace robo_waiter
{

struct Table
{

typedef TableRequest Request;
typedef TableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Table
} // namespace robo_waiter


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robo_waiter::Table > {
  static const char* value()
  {
    return "d9bc86335236069bddf3bda6b288eda2";
  }

  static const char* value(const ::robo_waiter::Table&) { return value(); }
};

template<>
struct DataType< ::robo_waiter::Table > {
  static const char* value()
  {
    return "robo_waiter/Table";
  }

  static const char* value(const ::robo_waiter::Table&) { return value(); }
};


// service_traits::MD5Sum< ::robo_waiter::TableRequest> should match 
// service_traits::MD5Sum< ::robo_waiter::Table > 
template<>
struct MD5Sum< ::robo_waiter::TableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robo_waiter::Table >::value();
  }
  static const char* value(const ::robo_waiter::TableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robo_waiter::TableRequest> should match 
// service_traits::DataType< ::robo_waiter::Table > 
template<>
struct DataType< ::robo_waiter::TableRequest>
{
  static const char* value()
  {
    return DataType< ::robo_waiter::Table >::value();
  }
  static const char* value(const ::robo_waiter::TableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robo_waiter::TableResponse> should match 
// service_traits::MD5Sum< ::robo_waiter::Table > 
template<>
struct MD5Sum< ::robo_waiter::TableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robo_waiter::Table >::value();
  }
  static const char* value(const ::robo_waiter::TableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robo_waiter::TableResponse> should match 
// service_traits::DataType< ::robo_waiter::Table > 
template<>
struct DataType< ::robo_waiter::TableResponse>
{
  static const char* value()
  {
    return DataType< ::robo_waiter::Table >::value();
  }
  static const char* value(const ::robo_waiter::TableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBO_WAITER_MESSAGE_TABLE_H
