// Generated by gencpp from file robo_waiter/Tl_gl.msg
// DO NOT EDIT!


#ifndef ROBO_WAITER_MESSAGE_TL_GL_H
#define ROBO_WAITER_MESSAGE_TL_GL_H

#include <ros/service_traits.h>


#include <robo_waiter/Tl_glRequest.h>
#include <robo_waiter/Tl_glResponse.h>


namespace robo_waiter
{

struct Tl_gl
{

typedef Tl_glRequest Request;
typedef Tl_glResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Tl_gl
} // namespace robo_waiter


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robo_waiter::Tl_gl > {
  static const char* value()
  {
    return "845a03915f6be3b247beed805d731b4d";
  }

  static const char* value(const ::robo_waiter::Tl_gl&) { return value(); }
};

template<>
struct DataType< ::robo_waiter::Tl_gl > {
  static const char* value()
  {
    return "robo_waiter/Tl_gl";
  }

  static const char* value(const ::robo_waiter::Tl_gl&) { return value(); }
};


// service_traits::MD5Sum< ::robo_waiter::Tl_glRequest> should match 
// service_traits::MD5Sum< ::robo_waiter::Tl_gl > 
template<>
struct MD5Sum< ::robo_waiter::Tl_glRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robo_waiter::Tl_gl >::value();
  }
  static const char* value(const ::robo_waiter::Tl_glRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robo_waiter::Tl_glRequest> should match 
// service_traits::DataType< ::robo_waiter::Tl_gl > 
template<>
struct DataType< ::robo_waiter::Tl_glRequest>
{
  static const char* value()
  {
    return DataType< ::robo_waiter::Tl_gl >::value();
  }
  static const char* value(const ::robo_waiter::Tl_glRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robo_waiter::Tl_glResponse> should match 
// service_traits::MD5Sum< ::robo_waiter::Tl_gl > 
template<>
struct MD5Sum< ::robo_waiter::Tl_glResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robo_waiter::Tl_gl >::value();
  }
  static const char* value(const ::robo_waiter::Tl_glResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robo_waiter::Tl_glResponse> should match 
// service_traits::DataType< ::robo_waiter::Tl_gl > 
template<>
struct DataType< ::robo_waiter::Tl_glResponse>
{
  static const char* value()
  {
    return DataType< ::robo_waiter::Tl_gl >::value();
  }
  static const char* value(const ::robo_waiter::Tl_glResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBO_WAITER_MESSAGE_TL_GL_H
