#boundary of robo overall shape.. example baselink is (0,0), left corner of shape (2,2) means corner x is offset 2 meter from baselink 
footprint: [[-0.4, -0.3], [-0.4, 0.3], [0.4, 0.3], [0.4, -0.3]] 
footprint_padding: 0.01 #like inflation radius of each corner to the robot

robot_base_frame: base_link
transform_tolerance: 1

resolution: 0.05

obstacle_range: 3
raytrace_range: 3
