#boundary of robo overall shape.. example baselink is (0,0), left corner of shape (2,2) means corner x is offset 2 meter from baselink 
footprint: [[-0.72, -0.40], [-0.72, 0.40], [0.72, 0.40], [0.72, -0.40]] # [[-0.68, -0.34], [-0.68, 0.34], [0.68, 0.34], [0.68, -0.34]]
footprint_padding: 0.10 #like inflation radius of each corner to the robot

robot_base_frame: base_link
transform_tolerance: 1

resolution: 0.05

obstacle_range: 6
raytrace_range: 6
