global_frame: map
rolling_window: false
track_unknown_space: true
#publish_frequency: 1.0
#update_frequency: 2.0


plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}
  - {name: obstacles,               type: "costmap_2d::ObstacleLayer"}




#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles:
    observation_sources: 3dlaser
    3dlaser: {data_type: PointCloud2, clearing: true, marking: true, topic: /velodyne_points, max_obstacle_height: 0.8, min_obstacle_height: 0.04}

inflation:
    inflation_radius: 0.3
    cost_scaling_factor: 0.5

