global_frame: map
rolling_window: false
track_unknown_space: true
#publish_frequency: 1.0
#update_frequency: 2.0


plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}




#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true


