global_frame: map
rolling_window: true
width: 7.0
height: 7.0
publish_frequency: 3
update_frequency: 5.0


plugins:
  - {name: obstacles,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,           type: "costmap_2d::InflationLayer"}



obstacles:
    observation_sources: 3dlaser
    3dlaser: {data_type: PointCloud2, clearing: true, marking: true, topic: /velodyne_points, max_obstacle_height: 0.8, min_obstacle_height: 0.04}

inflation:
    inflation_radius: 0.2
    cost_scaling_factor: 0.5

