controller_frequency: 5.0
recovery_behaviour_enabled: true
oscillation_distance: 0.5
oscillation_timeout: 10 #change later
planner_patience: 5
controller_patience: 5
recovery_behaviors:
  - {name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}
  - {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}

GlobalPlanner: # Also see: http://wiki.ros.org/global_planner

  allow_unknown: true # Allow planner to plan through unknown space, default true
  #Needs to have track_unknown_space: true in the obstacle / voxel layer (in costmap_commons_param) to work
  default_tolerance: 0.2 # If goal in obstacle, plan to the closest point in radius default_tolerance, default 0.0
  visualize_potential: true # Specifies whether or not to visualize the potential area computed via a PointCloud2.
  use_dijkstra: true # Use dijkstra's algorithm. Otherwise, A*, default true
  use_quadratic: true # Use the quadratic approximation of the potential. Otherwise, use a simpler calculation, default true
  use_grid_path: false # Create a path that follows the grid boundaries. Otherwise, use a gradient descent method, default false
  old_navfn_behavior: false # Exactly mirror behavior of navfn, use defaults for other boolean parameters, default false
  lethal_cost: 253 # default 253
  neutral_cost: 50 # default 50
  cost_factor: 3.0 # Factor to multiply each cost from costmap by, default 3.0
  publish_potential: true # Publish Potential Costmap (this is not like the navfn pointcloud2 potential), default true

  planner_window_x: 0.0 # default 0.0
  planner_window_y: 0.0 # default 0.0
  publish_scale: 100 # Scale by which the published potential gets multiplied, default 100
  planner_costmap_publish_frequency: 0.0 # default 0.0
#  orientation_mode: 1


DWAPlannerROS:
  # Robot configuration parameters
  acc_lim_x: 2.5
  acc_lim_y: 0
  acc_lim_th: 0.5 #0.5

  max_vel_x: 0.5
  min_vel_x: 0.0
  max_vel_y: 0
  min_vel_y: 0

  max_trans_vel: 0.5
  min_trans_vel: 0.1
  max_rot_vel: 1.5 #1.5
  min_rot_vel: 0.2 #0.2

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.05 #0.2
  xy_goal_tolerance: 0.05 #0.1
  latch_xy_goal_tolerance: true

  # Forward Simulation Parameters
  sim_time: 3.0
  sim_granularity: 0.02
  vx_samples: 20 #50
  vy_samples: 1
  vth_samples: 40 #50
   #penalize_negative_x: trues

  # Trajectory scoring parameters
  path_distance_bias: 7 # 20.0 The weighting for how much the controller should stay close to the path it was given
  goal_distance_bias: 1 # 30.0The weighting for how much the controller should attempt to reach its local goal, also controls speed
  occdist_scale: 0.1 # The weighting for how much the controller should attempt to avoid obstacles
  forward_point_distance: 0 # The distance from the center point of the robot to place an additional scoring point, in meters
  # stop_time_buffer: 0.2  # The amount of time that the robot must stThe absolute value of the veolicty at which to start scaling the robot's footprint, in m/sop before a collision in order for a trajectory to be considered valid in seconds
  # scaling_speed: 0.25 # The absolute value of the veolicty at which to start scaling the robot's footprint, in m/s
  # max_scaling_factor: 0.05 # The maximum factor to scale the robot's footprint by (0.2)

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05 #How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)
  #Debug
  publish_traj_pc : true
  publish_cost_grid_pc: true
  prune_plan: true

SBPLLatticePlanner:
  environment_type: XYThetaLattice
  planner_type: ARAPlanner
  allocated_time: 5.0
  initial_epsilon: 3.0
  forward_search: false

WaypointGlobalPlanner:
  epsilon: 1e-1  # distance threshold for final waypoint
  waypoints_per_meter: 20  # number of waypoints per meter for the interpolation of the path

TebLocalPlannerROS:

  odom_topic: odom
  map_frame: /map
    
 # Trajectory
  
  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: True
  max_global_plan_lookahead_dist: 3.0
  feasibility_check_no_poses: 5
    
 # Robot
         
  max_vel_x: 0.5
  max_vel_x_backwards: 0.2
  max_vel_theta: 0.3
  acc_lim_x: 2.5
  acc_lim_theta: 0.5
  min_turning_radius: 0.0
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "polygon"
    vertices: [ [-0.2675, -0.2375], [-0.2675, 0.2375], [0.2675, 0.2375], [0.2675, -0.2375] ] # for type "polygon"

 # GoalTolerance
    
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  free_goal_vel: False
    
 # Obstacles
    
  min_obstacle_dist: 0.4
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5

 # Optimization
    
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  weight_max_vel_x: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 1
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 1
  weight_obstacle: 50
  weight_dynamic_obstacle: 10 # not in use yet
  alternative_time_cost: False # not in use yet

 # Homotopy Class Planner

  enable_homotopy_class_planning: True
  enable_multithreading: True
  simple_exploration: False
  max_number_classes: 4
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: False

FTCPlanner:
  max_x_vel: 0.5
  max_rotation_vel: 1.0
  min_rotation_vel: 0.4
  acceleration_x: 0.5
  acceleration_z: 0.5
  position_accuracy: 0.04
  rotation_accuracy: 0.03
  slow_down_factor: 2.5
  sim_time: 0.6
  local_planner_frequence: 5
  join_obstacle: false

EBandPlannerROS:

 
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.05
  rot_stopped_vel: 0.01
  trans_stopped_vel: 0.01
#Visualization Parameter
  marker_lifetime: 1.5
#Elastic Band Parameter
  eband_min_relative_overlap: 2.1
  eband_tiny_bubble_distance: 0.5
  eband_tiny_bubble_expansion: 0.5
  eband_internal_force_gain: 1.0
  eband_external_force_gain: 2.0
  num_iterations_eband_optimization: 10
  eband_equilibrium_approx_max_recursion_depth: 6
  eband_equilibrium_relative_overshoot: 0.55
  eband_significant_force_lower_bound: 0.25
  costmap_weight: 15.0
#Trajectory Controller Parameters
  max_vel_lin: 0.75
  max_vel_th: 1.0
  min_vel_lin: 0.1
  min_vel_th: 0.0
  min_in_place_vel_th: 0.0
  in_place_trans_vel: 0.0
  k_prop: 4.0
  k_damp: 3.5
  Ctrl_Rate: 10.0
  max_acceleration: 0.5
  virtual_mass: 0.75
  max_translational_acceleration: 0.5
  max_rotational_acceleration: 1.5
  rotation_correction_threshold: 0.5
  differential_drive: false
  bubble_velocity_multiplier: 2.0
  rotation_threshold_multiplier: 1.0
  disallow_hysteresis: true


