point_0:
  name: home
  pose: [-0.30307467370377716, -0.26342445016685273]
  orientation: [0.9990236172508647, 0.04417931840802624]
  adj_points: [0,4]  #fill with point numbers that  are connected to this point separated by comma ','
  connected_points: 4    #fill with points are connected to this point separated by comma ','

point_1:
  name: doorway
  pose: [2.4580318797054144, -0.11919272558956462]
  orientation: [0.014916715041868759, 0.9998887396167434]
  adj_points: [1,2,4]  #fill with point numbers that  are connected to this point separated by comma ','
  connected_points: 2,4   #fill with points are connected to this point separated by comma ','

point_2:
  name: table1
  pose: [2.5490985175350285, -1.6614864957431534]
  orientation: [-0.7245254641917668, 0.6892480335392368]
  adj_points: [2,1,3]  #fill with point numbers that  are connected to this point separated by comma ','
  connected_points: 1,3   #fill with points are connected to this point separated by comma ','

point_3:
  name: table2
  pose: [0.30058824430390774, -1.755257563148813]
  orientation: [0.9999797573577667, -0.006362772564073461]
  adj_points: [3,2,4,6]  #fill with point numbers that  are connected to this point separated by comma ','
  connected_points: 2,4,6   #fill with points are connected to this point separated by comma ','

point_4:
  name: center
  pose: [0.31654833520656284, -0.5901909685434077]
  orientation: [0.6801534782182486, 0.7330697416123643]
  adj_points: [4,0,1,3,5]  #fill with point numbers that  are connected to this point separated by comma ','
  connected_points: 0,1,3,5   #fill with points are connected to this point separated by comma ','

point_5:
  name: room
  pose: [0.365204738731075, 0.7469254922710807]
  orientation: [0.6918564973405074, 0.7220350317593494]
  adj_points: [5,4]  #fill with point numbers that  are connected to this point separated by comma ','
  connected_points: 4   #fill with points are connected to this point separated by comma ','

point_6:
  name: table3
  pose: [-0.058981252364438186, -3.5492041828325576]
  orientation: [-0.7186289552887644, 0.6953937191408757]
  adj_points: [6,3]  #fill with point numbers that  are connected to this point separated by comma ','
  connected_points: 3   #fill with points are connected to this point separated by comma ','

no_of_points: 7

