// Generated by gencpp from file path_planner/Goal.msg
// DO NOT EDIT!


#ifndef PATH_PLANNER_MESSAGE_GOAL_H
#define PATH_PLANNER_MESSAGE_GOAL_H

#include <ros/service_traits.h>


#include <path_planner/GoalRequest.h>
#include <path_planner/GoalResponse.h>


namespace path_planner
{

struct Goal
{

typedef GoalRequest Request;
typedef GoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Goal
} // namespace path_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_planner::Goal > {
  static const char* value()
  {
    return "257e57560eaef13378eb07b58da2c735";
  }

  static const char* value(const ::path_planner::Goal&) { return value(); }
};

template<>
struct DataType< ::path_planner::Goal > {
  static const char* value()
  {
    return "path_planner/Goal";
  }

  static const char* value(const ::path_planner::Goal&) { return value(); }
};


// service_traits::MD5Sum< ::path_planner::GoalRequest> should match 
// service_traits::MD5Sum< ::path_planner::Goal > 
template<>
struct MD5Sum< ::path_planner::GoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_planner::Goal >::value();
  }
  static const char* value(const ::path_planner::GoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planner::GoalRequest> should match 
// service_traits::DataType< ::path_planner::Goal > 
template<>
struct DataType< ::path_planner::GoalRequest>
{
  static const char* value()
  {
    return DataType< ::path_planner::Goal >::value();
  }
  static const char* value(const ::path_planner::GoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_planner::GoalResponse> should match 
// service_traits::MD5Sum< ::path_planner::Goal > 
template<>
struct MD5Sum< ::path_planner::GoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_planner::Goal >::value();
  }
  static const char* value(const ::path_planner::GoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planner::GoalResponse> should match 
// service_traits::DataType< ::path_planner::Goal > 
template<>
struct DataType< ::path_planner::GoalResponse>
{
  static const char* value()
  {
    return DataType< ::path_planner::Goal >::value();
  }
  static const char* value(const ::path_planner::GoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_PLANNER_MESSAGE_GOAL_H
