// Generated by gencpp from file path_planner/Graph.msg
// DO NOT EDIT!


#ifndef PATH_PLANNER_MESSAGE_GRAPH_H
#define PATH_PLANNER_MESSAGE_GRAPH_H

#include <ros/service_traits.h>


#include <path_planner/GraphRequest.h>
#include <path_planner/GraphResponse.h>


namespace path_planner
{

struct Graph
{

typedef GraphRequest Request;
typedef GraphResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Graph
} // namespace path_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_planner::Graph > {
  static const char* value()
  {
    return "27d2326ebcb7de158de4e69732269ca9";
  }

  static const char* value(const ::path_planner::Graph&) { return value(); }
};

template<>
struct DataType< ::path_planner::Graph > {
  static const char* value()
  {
    return "path_planner/Graph";
  }

  static const char* value(const ::path_planner::Graph&) { return value(); }
};


// service_traits::MD5Sum< ::path_planner::GraphRequest> should match 
// service_traits::MD5Sum< ::path_planner::Graph > 
template<>
struct MD5Sum< ::path_planner::GraphRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_planner::Graph >::value();
  }
  static const char* value(const ::path_planner::GraphRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planner::GraphRequest> should match 
// service_traits::DataType< ::path_planner::Graph > 
template<>
struct DataType< ::path_planner::GraphRequest>
{
  static const char* value()
  {
    return DataType< ::path_planner::Graph >::value();
  }
  static const char* value(const ::path_planner::GraphRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_planner::GraphResponse> should match 
// service_traits::MD5Sum< ::path_planner::Graph > 
template<>
struct MD5Sum< ::path_planner::GraphResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_planner::Graph >::value();
  }
  static const char* value(const ::path_planner::GraphResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planner::GraphResponse> should match 
// service_traits::DataType< ::path_planner::Graph > 
template<>
struct DataType< ::path_planner::GraphResponse>
{
  static const char* value()
  {
    return DataType< ::path_planner::Graph >::value();
  }
  static const char* value(const ::path_planner::GraphResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_PLANNER_MESSAGE_GRAPH_H
