// Generated by gencpp from file path_planner/Manager.msg
// DO NOT EDIT!


#ifndef PATH_PLANNER_MESSAGE_MANAGER_H
#define PATH_PLANNER_MESSAGE_MANAGER_H

#include <ros/service_traits.h>


#include <path_planner/ManagerRequest.h>
#include <path_planner/ManagerResponse.h>


namespace path_planner
{

struct Manager
{

typedef ManagerRequest Request;
typedef ManagerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Manager
} // namespace path_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_planner::Manager > {
  static const char* value()
  {
    return "e39df53132eef39cca149f18cce9cea9";
  }

  static const char* value(const ::path_planner::Manager&) { return value(); }
};

template<>
struct DataType< ::path_planner::Manager > {
  static const char* value()
  {
    return "path_planner/Manager";
  }

  static const char* value(const ::path_planner::Manager&) { return value(); }
};


// service_traits::MD5Sum< ::path_planner::ManagerRequest> should match 
// service_traits::MD5Sum< ::path_planner::Manager > 
template<>
struct MD5Sum< ::path_planner::ManagerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_planner::Manager >::value();
  }
  static const char* value(const ::path_planner::ManagerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planner::ManagerRequest> should match 
// service_traits::DataType< ::path_planner::Manager > 
template<>
struct DataType< ::path_planner::ManagerRequest>
{
  static const char* value()
  {
    return DataType< ::path_planner::Manager >::value();
  }
  static const char* value(const ::path_planner::ManagerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_planner::ManagerResponse> should match 
// service_traits::MD5Sum< ::path_planner::Manager > 
template<>
struct MD5Sum< ::path_planner::ManagerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_planner::Manager >::value();
  }
  static const char* value(const ::path_planner::ManagerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planner::ManagerResponse> should match 
// service_traits::DataType< ::path_planner::Manager > 
template<>
struct DataType< ::path_planner::ManagerResponse>
{
  static const char* value()
  {
    return DataType< ::path_planner::Manager >::value();
  }
  static const char* value(const ::path_planner::ManagerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_PLANNER_MESSAGE_MANAGER_H
