// Generated by gencpp from file path_planner/PathFinderResponse.msg
// DO NOT EDIT!


#ifndef PATH_PLANNER_MESSAGE_PATHFINDERRESPONSE_H
#define PATH_PLANNER_MESSAGE_PATHFINDERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_planner
{
template <class ContainerAllocator>
struct PathFinderResponse_
{
  typedef PathFinderResponse_<ContainerAllocator> Type;

  PathFinderResponse_()
    : path()  {
    }
  PathFinderResponse_(const ContainerAllocator& _alloc)
    : path(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::path_planner::PathFinderResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_planner::PathFinderResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PathFinderResponse_

typedef ::path_planner::PathFinderResponse_<std::allocator<void> > PathFinderResponse;

typedef boost::shared_ptr< ::path_planner::PathFinderResponse > PathFinderResponsePtr;
typedef boost::shared_ptr< ::path_planner::PathFinderResponse const> PathFinderResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_planner::PathFinderResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_planner::PathFinderResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path_planner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roadmap_global_planner_msgs': ['/home/katomaran-ros/catkin_ws8/src/roadmap_global_planner_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path_planner::PathFinderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_planner::PathFinderResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planner::PathFinderResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planner::PathFinderResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planner::PathFinderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planner::PathFinderResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_planner::PathFinderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "022981802e636d133c6ed314a501f5ae";
  }

  static const char* value(const ::path_planner::PathFinderResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x022981802e636d13ULL;
  static const uint64_t static_value2 = 0x3c6ed314a501f5aeULL;
};

template<class ContainerAllocator>
struct DataType< ::path_planner::PathFinderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_planner/PathFinderResponse";
  }

  static const char* value(const ::path_planner::PathFinderResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_planner::PathFinderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] path\n\
\n\
";
  }

  static const char* value(const ::path_planner::PathFinderResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_planner::PathFinderResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathFinderResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_planner::PathFinderResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_planner::PathFinderResponse_<ContainerAllocator>& v)
  {
    s << indent << "path[]" << std::endl;
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      s << indent << "  path[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.path[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_PLANNER_MESSAGE_PATHFINDERRESPONSE_H
