// Generated by gencpp from file path_follower/GoalLoad.msg
// DO NOT EDIT!


#ifndef PATH_FOLLOWER_MESSAGE_GOALLOAD_H
#define PATH_FOLLOWER_MESSAGE_GOALLOAD_H

#include <ros/service_traits.h>


#include <path_follower/GoalLoadRequest.h>
#include <path_follower/GoalLoadResponse.h>


namespace path_follower
{

struct GoalLoad
{

typedef GoalLoadRequest Request;
typedef GoalLoadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoalLoad
} // namespace path_follower


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_follower::GoalLoad > {
  static const char* value()
  {
    return "56720ff27a89ff4af57b4a5f223bac21";
  }

  static const char* value(const ::path_follower::GoalLoad&) { return value(); }
};

template<>
struct DataType< ::path_follower::GoalLoad > {
  static const char* value()
  {
    return "path_follower/GoalLoad";
  }

  static const char* value(const ::path_follower::GoalLoad&) { return value(); }
};


// service_traits::MD5Sum< ::path_follower::GoalLoadRequest> should match 
// service_traits::MD5Sum< ::path_follower::GoalLoad > 
template<>
struct MD5Sum< ::path_follower::GoalLoadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_follower::GoalLoad >::value();
  }
  static const char* value(const ::path_follower::GoalLoadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_follower::GoalLoadRequest> should match 
// service_traits::DataType< ::path_follower::GoalLoad > 
template<>
struct DataType< ::path_follower::GoalLoadRequest>
{
  static const char* value()
  {
    return DataType< ::path_follower::GoalLoad >::value();
  }
  static const char* value(const ::path_follower::GoalLoadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_follower::GoalLoadResponse> should match 
// service_traits::MD5Sum< ::path_follower::GoalLoad > 
template<>
struct MD5Sum< ::path_follower::GoalLoadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_follower::GoalLoad >::value();
  }
  static const char* value(const ::path_follower::GoalLoadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_follower::GoalLoadResponse> should match 
// service_traits::DataType< ::path_follower::GoalLoad > 
template<>
struct DataType< ::path_follower::GoalLoadResponse>
{
  static const char* value()
  {
    return DataType< ::path_follower::GoalLoad >::value();
  }
  static const char* value(const ::path_follower::GoalLoadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_FOLLOWER_MESSAGE_GOALLOAD_H
