// Generated by gencpp from file path_follower/PointLoad.msg
// DO NOT EDIT!


#ifndef PATH_FOLLOWER_MESSAGE_POINTLOAD_H
#define PATH_FOLLOWER_MESSAGE_POINTLOAD_H

#include <ros/service_traits.h>


#include <path_follower/PointLoadRequest.h>
#include <path_follower/PointLoadResponse.h>


namespace path_follower
{

struct PointLoad
{

typedef PointLoadRequest Request;
typedef PointLoadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PointLoad
} // namespace path_follower


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_follower::PointLoad > {
  static const char* value()
  {
    return "ff86ebb20f757b817971f1cfe32bdb6b";
  }

  static const char* value(const ::path_follower::PointLoad&) { return value(); }
};

template<>
struct DataType< ::path_follower::PointLoad > {
  static const char* value()
  {
    return "path_follower/PointLoad";
  }

  static const char* value(const ::path_follower::PointLoad&) { return value(); }
};


// service_traits::MD5Sum< ::path_follower::PointLoadRequest> should match 
// service_traits::MD5Sum< ::path_follower::PointLoad > 
template<>
struct MD5Sum< ::path_follower::PointLoadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_follower::PointLoad >::value();
  }
  static const char* value(const ::path_follower::PointLoadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_follower::PointLoadRequest> should match 
// service_traits::DataType< ::path_follower::PointLoad > 
template<>
struct DataType< ::path_follower::PointLoadRequest>
{
  static const char* value()
  {
    return DataType< ::path_follower::PointLoad >::value();
  }
  static const char* value(const ::path_follower::PointLoadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_follower::PointLoadResponse> should match 
// service_traits::MD5Sum< ::path_follower::PointLoad > 
template<>
struct MD5Sum< ::path_follower::PointLoadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_follower::PointLoad >::value();
  }
  static const char* value(const ::path_follower::PointLoadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_follower::PointLoadResponse> should match 
// service_traits::DataType< ::path_follower::PointLoad > 
template<>
struct DataType< ::path_follower::PointLoadResponse>
{
  static const char* value()
  {
    return DataType< ::path_follower::PointLoad >::value();
  }
  static const char* value(const ::path_follower::PointLoadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_FOLLOWER_MESSAGE_POINTLOAD_H
