// Generated by gencpp from file path_follower/PointLoadRequest.msg
// DO NOT EDIT!


#ifndef PATH_FOLLOWER_MESSAGE_POINTLOADREQUEST_H
#define PATH_FOLLOWER_MESSAGE_POINTLOADREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <path_follower/PointList.h>

namespace path_follower
{
template <class ContainerAllocator>
struct PointLoadRequest_
{
  typedef PointLoadRequest_<ContainerAllocator> Type;

  PointLoadRequest_()
    : point_list()  {
    }
  PointLoadRequest_(const ContainerAllocator& _alloc)
    : point_list(_alloc)  {
  (void)_alloc;
    }



   typedef  ::path_follower::PointList_<ContainerAllocator>  _point_list_type;
  _point_list_type point_list;





  typedef boost::shared_ptr< ::path_follower::PointLoadRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_follower::PointLoadRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PointLoadRequest_

typedef ::path_follower::PointLoadRequest_<std::allocator<void> > PointLoadRequest;

typedef boost::shared_ptr< ::path_follower::PointLoadRequest > PointLoadRequestPtr;
typedef boost::shared_ptr< ::path_follower::PointLoadRequest const> PointLoadRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_follower::PointLoadRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_follower::PointLoadRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path_follower

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'path_follower': ['/home/katomaran-ros/catkin_ws8/src/path_follower/msg', '/home/katomaran-ros/catkin_ws8/src/path_follower/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path_follower::PointLoadRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_follower::PointLoadRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_follower::PointLoadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_follower::PointLoadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_follower::PointLoadRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_follower::PointLoadRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_follower::PointLoadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "197fec9f10f108cb96e1c9f3419973ff";
  }

  static const char* value(const ::path_follower::PointLoadRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x197fec9f10f108cbULL;
  static const uint64_t static_value2 = 0x96e1c9f3419973ffULL;
};

template<class ContainerAllocator>
struct DataType< ::path_follower::PointLoadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_follower/PointLoadRequest";
  }

  static const char* value(const ::path_follower::PointLoadRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_follower::PointLoadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_follower/PointList point_list\n\
\n\
================================================================================\n\
MSG: path_follower/PointList\n\
path_follower/PoseList[] pose_list\n\
\n\
================================================================================\n\
MSG: path_follower/PoseList\n\
float32[] list\n\
";
  }

  static const char* value(const ::path_follower::PointLoadRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_follower::PointLoadRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointLoadRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_follower::PointLoadRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_follower::PointLoadRequest_<ContainerAllocator>& v)
  {
    s << indent << "point_list: ";
    s << std::endl;
    Printer< ::path_follower::PointList_<ContainerAllocator> >::stream(s, indent + "  ", v.point_list);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_FOLLOWER_MESSAGE_POINTLOADREQUEST_H
