// Generated by gencpp from file path_follower/PointList.msg
// DO NOT EDIT!


#ifndef PATH_FOLLOWER_MESSAGE_POINTLIST_H
#define PATH_FOLLOWER_MESSAGE_POINTLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <path_follower/PoseList.h>

namespace path_follower
{
template <class ContainerAllocator>
struct PointList_
{
  typedef PointList_<ContainerAllocator> Type;

  PointList_()
    : pose_list()  {
    }
  PointList_(const ContainerAllocator& _alloc)
    : pose_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::path_follower::PoseList_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::path_follower::PoseList_<ContainerAllocator> >::other >  _pose_list_type;
  _pose_list_type pose_list;





  typedef boost::shared_ptr< ::path_follower::PointList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_follower::PointList_<ContainerAllocator> const> ConstPtr;

}; // struct PointList_

typedef ::path_follower::PointList_<std::allocator<void> > PointList;

typedef boost::shared_ptr< ::path_follower::PointList > PointListPtr;
typedef boost::shared_ptr< ::path_follower::PointList const> PointListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_follower::PointList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_follower::PointList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path_follower

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'path_follower': ['/home/katomaran-ros/catkin_ws8/src/path_follower/msg', '/home/katomaran-ros/catkin_ws8/src/path_follower/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path_follower::PointList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_follower::PointList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_follower::PointList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_follower::PointList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_follower::PointList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_follower::PointList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_follower::PointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f639923d0e4b33008c322b16a61c2555";
  }

  static const char* value(const ::path_follower::PointList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf639923d0e4b3300ULL;
  static const uint64_t static_value2 = 0x8c322b16a61c2555ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_follower::PointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_follower/PointList";
  }

  static const char* value(const ::path_follower::PointList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_follower::PointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_follower/PoseList[] pose_list\n\
\n\
================================================================================\n\
MSG: path_follower/PoseList\n\
float32[] list\n\
";
  }

  static const char* value(const ::path_follower::PointList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_follower::PointList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_follower::PointList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_follower::PointList_<ContainerAllocator>& v)
  {
    s << indent << "pose_list[]" << std::endl;
    for (size_t i = 0; i < v.pose_list.size(); ++i)
    {
      s << indent << "  pose_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::path_follower::PoseList_<ContainerAllocator> >::stream(s, indent + "    ", v.pose_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_FOLLOWER_MESSAGE_POINTLIST_H
