// Generated by gencpp from file patrol_planner/GetPlan.msg
// DO NOT EDIT!


#ifndef PATROL_PLANNER_MESSAGE_GETPLAN_H
#define PATROL_PLANNER_MESSAGE_GETPLAN_H

#include <ros/service_traits.h>


#include <patrol_planner/GetPlanRequest.h>
#include <patrol_planner/GetPlanResponse.h>


namespace patrol_planner
{

struct GetPlan
{

typedef GetPlanRequest Request;
typedef GetPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPlan
} // namespace patrol_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::patrol_planner::GetPlan > {
  static const char* value()
  {
    return "9d6b4f0ff14cc81eb21e6cb1c02a5f48";
  }

  static const char* value(const ::patrol_planner::GetPlan&) { return value(); }
};

template<>
struct DataType< ::patrol_planner::GetPlan > {
  static const char* value()
  {
    return "patrol_planner/GetPlan";
  }

  static const char* value(const ::patrol_planner::GetPlan&) { return value(); }
};


// service_traits::MD5Sum< ::patrol_planner::GetPlanRequest> should match 
// service_traits::MD5Sum< ::patrol_planner::GetPlan > 
template<>
struct MD5Sum< ::patrol_planner::GetPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::patrol_planner::GetPlan >::value();
  }
  static const char* value(const ::patrol_planner::GetPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::patrol_planner::GetPlanRequest> should match 
// service_traits::DataType< ::patrol_planner::GetPlan > 
template<>
struct DataType< ::patrol_planner::GetPlanRequest>
{
  static const char* value()
  {
    return DataType< ::patrol_planner::GetPlan >::value();
  }
  static const char* value(const ::patrol_planner::GetPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::patrol_planner::GetPlanResponse> should match 
// service_traits::MD5Sum< ::patrol_planner::GetPlan > 
template<>
struct MD5Sum< ::patrol_planner::GetPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::patrol_planner::GetPlan >::value();
  }
  static const char* value(const ::patrol_planner::GetPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::patrol_planner::GetPlanResponse> should match 
// service_traits::DataType< ::patrol_planner::GetPlan > 
template<>
struct DataType< ::patrol_planner::GetPlanResponse>
{
  static const char* value()
  {
    return DataType< ::patrol_planner::GetPlan >::value();
  }
  static const char* value(const ::patrol_planner::GetPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATROL_PLANNER_MESSAGE_GETPLAN_H
