// Generated by gencpp from file patrol_planner/GPSGoal.msg
// DO NOT EDIT!


#ifndef PATROL_PLANNER_MESSAGE_GPSGOAL_H
#define PATROL_PLANNER_MESSAGE_GPSGOAL_H

#include <ros/service_traits.h>


#include <patrol_planner/GPSGoalRequest.h>
#include <patrol_planner/GPSGoalResponse.h>


namespace patrol_planner
{

struct GPSGoal
{

typedef GPSGoalRequest Request;
typedef GPSGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GPSGoal
} // namespace patrol_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::patrol_planner::GPSGoal > {
  static const char* value()
  {
    return "069b6c0906fcffac7ddcf59faaf4b55a";
  }

  static const char* value(const ::patrol_planner::GPSGoal&) { return value(); }
};

template<>
struct DataType< ::patrol_planner::GPSGoal > {
  static const char* value()
  {
    return "patrol_planner/GPSGoal";
  }

  static const char* value(const ::patrol_planner::GPSGoal&) { return value(); }
};


// service_traits::MD5Sum< ::patrol_planner::GPSGoalRequest> should match 
// service_traits::MD5Sum< ::patrol_planner::GPSGoal > 
template<>
struct MD5Sum< ::patrol_planner::GPSGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::patrol_planner::GPSGoal >::value();
  }
  static const char* value(const ::patrol_planner::GPSGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::patrol_planner::GPSGoalRequest> should match 
// service_traits::DataType< ::patrol_planner::GPSGoal > 
template<>
struct DataType< ::patrol_planner::GPSGoalRequest>
{
  static const char* value()
  {
    return DataType< ::patrol_planner::GPSGoal >::value();
  }
  static const char* value(const ::patrol_planner::GPSGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::patrol_planner::GPSGoalResponse> should match 
// service_traits::MD5Sum< ::patrol_planner::GPSGoal > 
template<>
struct MD5Sum< ::patrol_planner::GPSGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::patrol_planner::GPSGoal >::value();
  }
  static const char* value(const ::patrol_planner::GPSGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::patrol_planner::GPSGoalResponse> should match 
// service_traits::DataType< ::patrol_planner::GPSGoal > 
template<>
struct DataType< ::patrol_planner::GPSGoalResponse>
{
  static const char* value()
  {
    return DataType< ::patrol_planner::GPSGoal >::value();
  }
  static const char* value(const ::patrol_planner::GPSGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATROL_PLANNER_MESSAGE_GPSGOAL_H
