// Generated by gencpp from file patrol_planner/GPSGoalResponse.msg
// DO NOT EDIT!


#ifndef PATROL_PLANNER_MESSAGE_GPSGOALRESPONSE_H
#define PATROL_PLANNER_MESSAGE_GPSGOALRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace patrol_planner
{
template <class ContainerAllocator>
struct GPSGoalResponse_
{
  typedef GPSGoalResponse_<ContainerAllocator> Type;

  GPSGoalResponse_()
    : goal_sent_status(false)  {
    }
  GPSGoalResponse_(const ContainerAllocator& _alloc)
    : goal_sent_status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _goal_sent_status_type;
  _goal_sent_status_type goal_sent_status;





  typedef boost::shared_ptr< ::patrol_planner::GPSGoalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::patrol_planner::GPSGoalResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GPSGoalResponse_

typedef ::patrol_planner::GPSGoalResponse_<std::allocator<void> > GPSGoalResponse;

typedef boost::shared_ptr< ::patrol_planner::GPSGoalResponse > GPSGoalResponsePtr;
typedef boost::shared_ptr< ::patrol_planner::GPSGoalResponse const> GPSGoalResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::patrol_planner::GPSGoalResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::patrol_planner::GPSGoalResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace patrol_planner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'patrol_planner': ['/home/katomaran-ros/catkin_ws8/src/patrol_planner/msg', '/home/katomaran-ros/catkin_ws8/src/patrol_planner/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::patrol_planner::GPSGoalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::patrol_planner::GPSGoalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::patrol_planner::GPSGoalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::patrol_planner::GPSGoalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::patrol_planner::GPSGoalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::patrol_planner::GPSGoalResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::patrol_planner::GPSGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a3379bd2e62a0c32a1f5bf665955c53e";
  }

  static const char* value(const ::patrol_planner::GPSGoalResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa3379bd2e62a0c32ULL;
  static const uint64_t static_value2 = 0xa1f5bf665955c53eULL;
};

template<class ContainerAllocator>
struct DataType< ::patrol_planner::GPSGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "patrol_planner/GPSGoalResponse";
  }

  static const char* value(const ::patrol_planner::GPSGoalResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::patrol_planner::GPSGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool goal_sent_status\n\
\n\
";
  }

  static const char* value(const ::patrol_planner::GPSGoalResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::patrol_planner::GPSGoalResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_sent_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GPSGoalResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::patrol_planner::GPSGoalResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::patrol_planner::GPSGoalResponse_<ContainerAllocator>& v)
  {
    s << indent << "goal_sent_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.goal_sent_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATROL_PLANNER_MESSAGE_GPSGOALRESPONSE_H
