// Generated by gencpp from file patrol_planner/Park.msg
// DO NOT EDIT!


#ifndef PATROL_PLANNER_MESSAGE_PARK_H
#define PATROL_PLANNER_MESSAGE_PARK_H

#include <ros/service_traits.h>


#include <patrol_planner/ParkRequest.h>
#include <patrol_planner/ParkResponse.h>


namespace patrol_planner
{

struct Park
{

typedef ParkRequest Request;
typedef ParkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Park
} // namespace patrol_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::patrol_planner::Park > {
  static const char* value()
  {
    return "4a4b2bdf33b9dce4f3e033bed4cd41b8";
  }

  static const char* value(const ::patrol_planner::Park&) { return value(); }
};

template<>
struct DataType< ::patrol_planner::Park > {
  static const char* value()
  {
    return "patrol_planner/Park";
  }

  static const char* value(const ::patrol_planner::Park&) { return value(); }
};


// service_traits::MD5Sum< ::patrol_planner::ParkRequest> should match 
// service_traits::MD5Sum< ::patrol_planner::Park > 
template<>
struct MD5Sum< ::patrol_planner::ParkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::patrol_planner::Park >::value();
  }
  static const char* value(const ::patrol_planner::ParkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::patrol_planner::ParkRequest> should match 
// service_traits::DataType< ::patrol_planner::Park > 
template<>
struct DataType< ::patrol_planner::ParkRequest>
{
  static const char* value()
  {
    return DataType< ::patrol_planner::Park >::value();
  }
  static const char* value(const ::patrol_planner::ParkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::patrol_planner::ParkResponse> should match 
// service_traits::MD5Sum< ::patrol_planner::Park > 
template<>
struct MD5Sum< ::patrol_planner::ParkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::patrol_planner::Park >::value();
  }
  static const char* value(const ::patrol_planner::ParkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::patrol_planner::ParkResponse> should match 
// service_traits::DataType< ::patrol_planner::Park > 
template<>
struct DataType< ::patrol_planner::ParkResponse>
{
  static const char* value()
  {
    return DataType< ::patrol_planner::Park >::value();
  }
  static const char* value(const ::patrol_planner::ParkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATROL_PLANNER_MESSAGE_PARK_H
