// Generated by gencpp from file patrol_planner/PathLoadResponse.msg
// DO NOT EDIT!


#ifndef PATROL_PLANNER_MESSAGE_PATHLOADRESPONSE_H
#define PATROL_PLANNER_MESSAGE_PATHLOADRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <patrol_planner/Milestone.h>

namespace patrol_planner
{
template <class ContainerAllocator>
struct PathLoadResponse_
{
  typedef PathLoadResponse_<ContainerAllocator> Type;

  PathLoadResponse_()
    : milestone_list()  {
    }
  PathLoadResponse_(const ContainerAllocator& _alloc)
    : milestone_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::patrol_planner::Milestone_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::patrol_planner::Milestone_<ContainerAllocator> >::other >  _milestone_list_type;
  _milestone_list_type milestone_list;





  typedef boost::shared_ptr< ::patrol_planner::PathLoadResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::patrol_planner::PathLoadResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PathLoadResponse_

typedef ::patrol_planner::PathLoadResponse_<std::allocator<void> > PathLoadResponse;

typedef boost::shared_ptr< ::patrol_planner::PathLoadResponse > PathLoadResponsePtr;
typedef boost::shared_ptr< ::patrol_planner::PathLoadResponse const> PathLoadResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::patrol_planner::PathLoadResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::patrol_planner::PathLoadResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace patrol_planner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'patrol_planner': ['/home/katomaran-ros/catkin_ws8/src/patrol_planner/msg', '/home/katomaran-ros/catkin_ws8/src/patrol_planner/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::patrol_planner::PathLoadResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::patrol_planner::PathLoadResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::patrol_planner::PathLoadResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::patrol_planner::PathLoadResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::patrol_planner::PathLoadResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::patrol_planner::PathLoadResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::patrol_planner::PathLoadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c0344da655de49cc9cb77b4e3877943b";
  }

  static const char* value(const ::patrol_planner::PathLoadResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc0344da655de49ccULL;
  static const uint64_t static_value2 = 0x9cb77b4e3877943bULL;
};

template<class ContainerAllocator>
struct DataType< ::patrol_planner::PathLoadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "patrol_planner/PathLoadResponse";
  }

  static const char* value(const ::patrol_planner::PathLoadResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::patrol_planner::PathLoadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Milestone[] milestone_list\n\
\n\
\n\
================================================================================\n\
MSG: patrol_planner/Milestone\n\
string name\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 w\n\
";
  }

  static const char* value(const ::patrol_planner::PathLoadResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::patrol_planner::PathLoadResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.milestone_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathLoadResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::patrol_planner::PathLoadResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::patrol_planner::PathLoadResponse_<ContainerAllocator>& v)
  {
    s << indent << "milestone_list[]" << std::endl;
    for (size_t i = 0; i < v.milestone_list.size(); ++i)
    {
      s << indent << "  milestone_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::patrol_planner::Milestone_<ContainerAllocator> >::stream(s, indent + "    ", v.milestone_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATROL_PLANNER_MESSAGE_PATHLOADRESPONSE_H
