// Generated by gencpp from file patrol_planner/PathLoad.msg
// DO NOT EDIT!


#ifndef PATROL_PLANNER_MESSAGE_PATHLOAD_H
#define PATROL_PLANNER_MESSAGE_PATHLOAD_H

#include <ros/service_traits.h>


#include <patrol_planner/PathLoadRequest.h>
#include <patrol_planner/PathLoadResponse.h>


namespace patrol_planner
{

struct PathLoad
{

typedef PathLoadRequest Request;
typedef PathLoadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PathLoad
} // namespace patrol_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::patrol_planner::PathLoad > {
  static const char* value()
  {
    return "813591a0b724e5a0e599fdf9d754d157";
  }

  static const char* value(const ::patrol_planner::PathLoad&) { return value(); }
};

template<>
struct DataType< ::patrol_planner::PathLoad > {
  static const char* value()
  {
    return "patrol_planner/PathLoad";
  }

  static const char* value(const ::patrol_planner::PathLoad&) { return value(); }
};


// service_traits::MD5Sum< ::patrol_planner::PathLoadRequest> should match 
// service_traits::MD5Sum< ::patrol_planner::PathLoad > 
template<>
struct MD5Sum< ::patrol_planner::PathLoadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::patrol_planner::PathLoad >::value();
  }
  static const char* value(const ::patrol_planner::PathLoadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::patrol_planner::PathLoadRequest> should match 
// service_traits::DataType< ::patrol_planner::PathLoad > 
template<>
struct DataType< ::patrol_planner::PathLoadRequest>
{
  static const char* value()
  {
    return DataType< ::patrol_planner::PathLoad >::value();
  }
  static const char* value(const ::patrol_planner::PathLoadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::patrol_planner::PathLoadResponse> should match 
// service_traits::MD5Sum< ::patrol_planner::PathLoad > 
template<>
struct MD5Sum< ::patrol_planner::PathLoadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::patrol_planner::PathLoad >::value();
  }
  static const char* value(const ::patrol_planner::PathLoadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::patrol_planner::PathLoadResponse> should match 
// service_traits::DataType< ::patrol_planner::PathLoad > 
template<>
struct DataType< ::patrol_planner::PathLoadResponse>
{
  static const char* value()
  {
    return DataType< ::patrol_planner::PathLoad >::value();
  }
  static const char* value(const ::patrol_planner::PathLoadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATROL_PLANNER_MESSAGE_PATHLOAD_H
