// Generated by gencpp from file patrol_planner/Pause.msg
// DO NOT EDIT!


#ifndef PATROL_PLANNER_MESSAGE_PAUSE_H
#define PATROL_PLANNER_MESSAGE_PAUSE_H

#include <ros/service_traits.h>


#include <patrol_planner/PauseRequest.h>
#include <patrol_planner/PauseResponse.h>


namespace patrol_planner
{

struct Pause
{

typedef PauseRequest Request;
typedef PauseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Pause
} // namespace patrol_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::patrol_planner::Pause > {
  static const char* value()
  {
    return "3dfb9d0014ecbba1e3c8cb189553972f";
  }

  static const char* value(const ::patrol_planner::Pause&) { return value(); }
};

template<>
struct DataType< ::patrol_planner::Pause > {
  static const char* value()
  {
    return "patrol_planner/Pause";
  }

  static const char* value(const ::patrol_planner::Pause&) { return value(); }
};


// service_traits::MD5Sum< ::patrol_planner::PauseRequest> should match 
// service_traits::MD5Sum< ::patrol_planner::Pause > 
template<>
struct MD5Sum< ::patrol_planner::PauseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::patrol_planner::Pause >::value();
  }
  static const char* value(const ::patrol_planner::PauseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::patrol_planner::PauseRequest> should match 
// service_traits::DataType< ::patrol_planner::Pause > 
template<>
struct DataType< ::patrol_planner::PauseRequest>
{
  static const char* value()
  {
    return DataType< ::patrol_planner::Pause >::value();
  }
  static const char* value(const ::patrol_planner::PauseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::patrol_planner::PauseResponse> should match 
// service_traits::MD5Sum< ::patrol_planner::Pause > 
template<>
struct MD5Sum< ::patrol_planner::PauseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::patrol_planner::Pause >::value();
  }
  static const char* value(const ::patrol_planner::PauseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::patrol_planner::PauseResponse> should match 
// service_traits::DataType< ::patrol_planner::Pause > 
template<>
struct DataType< ::patrol_planner::PauseResponse>
{
  static const char* value()
  {
    return DataType< ::patrol_planner::Pause >::value();
  }
  static const char* value(const ::patrol_planner::PauseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATROL_PLANNER_MESSAGE_PAUSE_H
