// Generated by gencpp from file patrol_planner/Save.msg
// DO NOT EDIT!


#ifndef PATROL_PLANNER_MESSAGE_SAVE_H
#define PATROL_PLANNER_MESSAGE_SAVE_H

#include <ros/service_traits.h>


#include <patrol_planner/SaveRequest.h>
#include <patrol_planner/SaveResponse.h>


namespace patrol_planner
{

struct Save
{

typedef SaveRequest Request;
typedef SaveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Save
} // namespace patrol_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::patrol_planner::Save > {
  static const char* value()
  {
    return "e39df53132eef39cca149f18cce9cea9";
  }

  static const char* value(const ::patrol_planner::Save&) { return value(); }
};

template<>
struct DataType< ::patrol_planner::Save > {
  static const char* value()
  {
    return "patrol_planner/Save";
  }

  static const char* value(const ::patrol_planner::Save&) { return value(); }
};


// service_traits::MD5Sum< ::patrol_planner::SaveRequest> should match 
// service_traits::MD5Sum< ::patrol_planner::Save > 
template<>
struct MD5Sum< ::patrol_planner::SaveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::patrol_planner::Save >::value();
  }
  static const char* value(const ::patrol_planner::SaveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::patrol_planner::SaveRequest> should match 
// service_traits::DataType< ::patrol_planner::Save > 
template<>
struct DataType< ::patrol_planner::SaveRequest>
{
  static const char* value()
  {
    return DataType< ::patrol_planner::Save >::value();
  }
  static const char* value(const ::patrol_planner::SaveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::patrol_planner::SaveResponse> should match 
// service_traits::MD5Sum< ::patrol_planner::Save > 
template<>
struct MD5Sum< ::patrol_planner::SaveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::patrol_planner::Save >::value();
  }
  static const char* value(const ::patrol_planner::SaveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::patrol_planner::SaveResponse> should match 
// service_traits::DataType< ::patrol_planner::Save > 
template<>
struct DataType< ::patrol_planner::SaveResponse>
{
  static const char* value()
  {
    return DataType< ::patrol_planner::Save >::value();
  }
  static const char* value(const ::patrol_planner::SaveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATROL_PLANNER_MESSAGE_SAVE_H
