// Generated by gencpp from file patrol_planner/Tl_gl.msg
// DO NOT EDIT!


#ifndef PATROL_PLANNER_MESSAGE_TL_GL_H
#define PATROL_PLANNER_MESSAGE_TL_GL_H

#include <ros/service_traits.h>


#include <patrol_planner/Tl_glRequest.h>
#include <patrol_planner/Tl_glResponse.h>


namespace patrol_planner
{

struct Tl_gl
{

typedef Tl_glRequest Request;
typedef Tl_glResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Tl_gl
} // namespace patrol_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::patrol_planner::Tl_gl > {
  static const char* value()
  {
    return "d9bc86335236069bddf3bda6b288eda2";
  }

  static const char* value(const ::patrol_planner::Tl_gl&) { return value(); }
};

template<>
struct DataType< ::patrol_planner::Tl_gl > {
  static const char* value()
  {
    return "patrol_planner/Tl_gl";
  }

  static const char* value(const ::patrol_planner::Tl_gl&) { return value(); }
};


// service_traits::MD5Sum< ::patrol_planner::Tl_glRequest> should match 
// service_traits::MD5Sum< ::patrol_planner::Tl_gl > 
template<>
struct MD5Sum< ::patrol_planner::Tl_glRequest>
{
  static const char* value()
  {
    return MD5Sum< ::patrol_planner::Tl_gl >::value();
  }
  static const char* value(const ::patrol_planner::Tl_glRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::patrol_planner::Tl_glRequest> should match 
// service_traits::DataType< ::patrol_planner::Tl_gl > 
template<>
struct DataType< ::patrol_planner::Tl_glRequest>
{
  static const char* value()
  {
    return DataType< ::patrol_planner::Tl_gl >::value();
  }
  static const char* value(const ::patrol_planner::Tl_glRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::patrol_planner::Tl_glResponse> should match 
// service_traits::MD5Sum< ::patrol_planner::Tl_gl > 
template<>
struct MD5Sum< ::patrol_planner::Tl_glResponse>
{
  static const char* value()
  {
    return MD5Sum< ::patrol_planner::Tl_gl >::value();
  }
  static const char* value(const ::patrol_planner::Tl_glResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::patrol_planner::Tl_glResponse> should match 
// service_traits::DataType< ::patrol_planner::Tl_gl > 
template<>
struct DataType< ::patrol_planner::Tl_glResponse>
{
  static const char* value()
  {
    return DataType< ::patrol_planner::Tl_gl >::value();
  }
  static const char* value(const ::patrol_planner::Tl_glResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATROL_PLANNER_MESSAGE_TL_GL_H
