// Generated by gencpp from file roadmap_global_planner_msgs/MapPair.msg
// DO NOT EDIT!


#ifndef ROADMAP_GLOBAL_PLANNER_MSGS_MESSAGE_MAPPAIR_H
#define ROADMAP_GLOBAL_PLANNER_MSGS_MESSAGE_MAPPAIR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace roadmap_global_planner_msgs
{
template <class ContainerAllocator>
struct MapPair_
{
  typedef MapPair_<ContainerAllocator> Type;

  MapPair_()
    : node(0)
    , pose()  {
    }
  MapPair_(const ContainerAllocator& _alloc)
    : node(0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _node_type;
  _node_type node;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::roadmap_global_planner_msgs::MapPair_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roadmap_global_planner_msgs::MapPair_<ContainerAllocator> const> ConstPtr;

}; // struct MapPair_

typedef ::roadmap_global_planner_msgs::MapPair_<std::allocator<void> > MapPair;

typedef boost::shared_ptr< ::roadmap_global_planner_msgs::MapPair > MapPairPtr;
typedef boost::shared_ptr< ::roadmap_global_planner_msgs::MapPair const> MapPairConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roadmap_global_planner_msgs::MapPair_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roadmap_global_planner_msgs::MapPair_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roadmap_global_planner_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roadmap_global_planner_msgs': ['/home/katomaran-ros/catkin_ws8/src/roadmap_global_planner_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roadmap_global_planner_msgs::MapPair_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roadmap_global_planner_msgs::MapPair_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roadmap_global_planner_msgs::MapPair_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roadmap_global_planner_msgs::MapPair_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roadmap_global_planner_msgs::MapPair_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roadmap_global_planner_msgs::MapPair_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roadmap_global_planner_msgs::MapPair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "70da0c8f55f16c16e0cd2b1120c67a6b";
  }

  static const char* value(const ::roadmap_global_planner_msgs::MapPair_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x70da0c8f55f16c16ULL;
  static const uint64_t static_value2 = 0xe0cd2b1120c67a6bULL;
};

template<class ContainerAllocator>
struct DataType< ::roadmap_global_planner_msgs::MapPair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roadmap_global_planner_msgs/MapPair";
  }

  static const char* value(const ::roadmap_global_planner_msgs::MapPair_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roadmap_global_planner_msgs::MapPair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 node\n\
geometry_msgs/Pose pose\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::roadmap_global_planner_msgs::MapPair_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roadmap_global_planner_msgs::MapPair_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.node);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapPair_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roadmap_global_planner_msgs::MapPair_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roadmap_global_planner_msgs::MapPair_<ContainerAllocator>& v)
  {
    s << indent << "node: ";
    Printer<int32_t>::stream(s, indent + "  ", v.node);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROADMAP_GLOBAL_PLANNER_MSGS_MESSAGE_MAPPAIR_H
