# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from my_change/Sonic.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Sonic(genpy.Message):
  _md5sum = "28ade20c4ac74f4cfe91fd6effaf9b2e"
  _type = "my_change/Sonic"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 no
float32 distance1
float32 distance2
float32 distance3
float32 distance4
float32 distance5

"""
  __slots__ = ['no','distance1','distance2','distance3','distance4','distance5']
  _slot_types = ['int32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       no,distance1,distance2,distance3,distance4,distance5

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Sonic, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.no is None:
        self.no = 0
      if self.distance1 is None:
        self.distance1 = 0.
      if self.distance2 is None:
        self.distance2 = 0.
      if self.distance3 is None:
        self.distance3 = 0.
      if self.distance4 is None:
        self.distance4 = 0.
      if self.distance5 is None:
        self.distance5 = 0.
    else:
      self.no = 0
      self.distance1 = 0.
      self.distance2 = 0.
      self.distance3 = 0.
      self.distance4 = 0.
      self.distance5 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_i5f.pack(_x.no, _x.distance1, _x.distance2, _x.distance3, _x.distance4, _x.distance5))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.no, _x.distance1, _x.distance2, _x.distance3, _x.distance4, _x.distance5,) = _struct_i5f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_i5f.pack(_x.no, _x.distance1, _x.distance2, _x.distance3, _x.distance4, _x.distance5))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.no, _x.distance1, _x.distance2, _x.distance3, _x.distance4, _x.distance5,) = _struct_i5f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i5f = struct.Struct("<i5f")
