# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roadmap_global_planner_msgs/AdjacencyList.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import roadmap_global_planner_msgs.msg
import geometry_msgs.msg

class AdjacencyList(genpy.Message):
  _md5sum = "d2f6aa9b2ba6558c5394addb6c9bfc26"
  _type = "roadmap_global_planner_msgs/AdjacencyList"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """roadmap_global_planner_msgs/PointList[] adj_list
roadmap_global_planner_msgs/MapPair[] map
================================================================================
MSG: roadmap_global_planner_msgs/PointList
int32[] list

================================================================================
MSG: roadmap_global_planner_msgs/MapPair
int32 node
geometry_msgs/Pose pose
================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

"""
  __slots__ = ['adj_list','map']
  _slot_types = ['roadmap_global_planner_msgs/PointList[]','roadmap_global_planner_msgs/MapPair[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       adj_list,map

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AdjacencyList, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.adj_list is None:
        self.adj_list = []
      if self.map is None:
        self.map = []
    else:
      self.adj_list = []
      self.map = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.adj_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.adj_list:
        length = len(val1.list)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(struct.pack(pattern, *val1.list))
      length = len(self.map)
      buff.write(_struct_I.pack(length))
      for val1 in self.map:
        buff.write(_struct_i.pack(val1.node))
        _v1 = val1.pose
        _v2 = _v1.position
        _x = _v2
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        _v3 = _v1.orientation
        _x = _v3
        buff.write(_struct_4d.pack(_x.x, _x.y, _x.z, _x.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.adj_list is None:
        self.adj_list = None
      if self.map is None:
        self.map = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.adj_list = []
      for i in range(0, length):
        val1 = roadmap_global_planner_msgs.msg.PointList()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        end += struct.calcsize(pattern)
        val1.list = struct.unpack(pattern, str[start:end])
        self.adj_list.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.map = []
      for i in range(0, length):
        val1 = roadmap_global_planner_msgs.msg.MapPair()
        start = end
        end += 4
        (val1.node,) = _struct_i.unpack(str[start:end])
        _v4 = val1.pose
        _v5 = _v4.position
        _x = _v5
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        _v6 = _v4.orientation
        _x = _v6
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _struct_4d.unpack(str[start:end])
        self.map.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.adj_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.adj_list:
        length = len(val1.list)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(val1.list.tostring())
      length = len(self.map)
      buff.write(_struct_I.pack(length))
      for val1 in self.map:
        buff.write(_struct_i.pack(val1.node))
        _v7 = val1.pose
        _v8 = _v7.position
        _x = _v8
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        _v9 = _v7.orientation
        _x = _v9
        buff.write(_struct_4d.pack(_x.x, _x.y, _x.z, _x.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.adj_list is None:
        self.adj_list = None
      if self.map is None:
        self.map = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.adj_list = []
      for i in range(0, length):
        val1 = roadmap_global_planner_msgs.msg.PointList()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        end += struct.calcsize(pattern)
        val1.list = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
        self.adj_list.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.map = []
      for i in range(0, length):
        val1 = roadmap_global_planner_msgs.msg.MapPair()
        start = end
        end += 4
        (val1.node,) = _struct_i.unpack(str[start:end])
        _v10 = val1.pose
        _v11 = _v10.position
        _x = _v11
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        _v12 = _v10.orientation
        _x = _v12
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _struct_4d.unpack(str[start:end])
        self.map.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i = struct.Struct("<i")
_struct_4d = struct.Struct("<4d")
_struct_3d = struct.Struct("<3d")
